CREATE TABLE [dbo].[Call] (
    [TelephonyCallId]      UNIQUEIDENTIFIER NOT NULL,
    [CallTo]               NVARCHAR (50)    NULL,
    [CallFrom]             NVARCHAR (50)    NULL,
    [Direction]            CHAR (13)        NULL,
    [Status]               CHAR (11)        NULL,
    [StartTime]            DATETIME         NULL,
    [EndTime]              DATETIME         NULL,
    [Duration]             INT              NULL,
    [Sid]                  CHAR (34)        NULL,
    [AccountSid]           CHAR (34)        NULL,
    [ParentCallSid]        CHAR (34)        NULL,
    [PhoneNumberSid]       CHAR (34)        NULL,
    [ForwardedFrom]        NVARCHAR (50)    NULL,
    [AnsweredBy]           CHAR (7)         NULL,
    [CallerName]           NVARCHAR (50)    NULL,
    [Price]                DECIMAL (9, 2)   NULL,
    [Uri]                  NVARCHAR (500)   NULL,
    [CallSessionType]      TINYINT          CONSTRAINT [DF_Call_CallType] DEFAULT ((0)) NULL,
    [RestExceptionStatus]  NVARCHAR (10)    NULL,
    [RestExceptionCode]    NVARCHAR (10)    NULL,
    [RestExceptionMessage] NVARCHAR (500)   NULL,
    [TwilioDateCreated]    DATETIME         NULL,
    [TwilioDateUpdated]    DATETIME         NULL,
    [Created]              DATETIME         NOT NULL,
    [Updated]              DATETIME         NOT NULL,
    CONSTRAINT [PK_Call] PRIMARY KEY CLUSTERED ([TelephonyCallId] ASC)
);

